{% load i18n %}
{
	'strings': {
		'app_title': '{% trans "Bangladesh" %}',
		'username': '{% trans "Username" %}',
		'password': '{% trans "Password" %}',
		'footer': '{% trans "&copy; Jamie Cockburn 2014" %}',
		'login': '{% trans "Login" %}',
		'logout': '{% trans "Logout" %}',
		'confirm_logout': '{% trans "Are you sure you want to logout?" %}',
		'home': '{% trans "Home" %}',
		'surveys': '{% trans "Surveys" %}',
		'survey': '{% trans "Survey" %}',
		'no_surveys': '{% trans "No surveys" %}',
		'title': '{% trans "Title" %}',
		'users': '{% trans "Users" %}',
		'live': '{% trans "Visible" %}',
		'live_column_tip': '{% trans "Indicates if the survey is visible" %}',
		'survey_live': '{% trans "This survey is visible" %}',
		'survey_not_live': '{% trans "This survey is not visible" %}',
		'open': '{% trans "Open" %}',
		'open_column_tip': '{% trans "Indicates if the survey is accepting new submissions" %}',
		'survey_open': '{% trans "This survey is accepting new submissions" %}',
		'survey_not_open': '{% trans "This survey is not accepting any submissions" %}',
		'new_survey': '{% trans "New Survey" %}',
		'edit_survey': '{% trans "Edit Survey" %}',
		'set_visible': '{% trans "Set Visible" %}',
		'set_hidden': '{% trans "Set Hidden" %}',
		'set_open': '{% trans "Set Open" %}',
		'set_closed': '{% trans "Set Closed" %}',
		'delete_survey': '{% trans "Delete Survey" %}',
	}
}
